language: node_js

os:
  -linux

node_js:
  - node

branches:
  only:
    - master
    - add-travis-ci
    - /^release-.*/

before_install:
  - npm i -g npm@6.7.0

install:
  - npm install
  - npm build

script:
  npm test